# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VkBMQeNdLvu2XfxYQWRP2SroatsR35K
"""

!pip install tensorflow tf-keras pillow numpy

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import numpy as np
from PIL import Image, ImageOps
import tf_keras as keras

np.set_printoptions(suppress=True)

model = keras.models.load_model("keras_model.h5", compile=False)
class_names = open("labels.txt", "r").readlines()

data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

image_path = "test.jpg"
image = Image.open(image_path).convert("RGB")

size = (224, 224)
image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)

image_array = np.asarray(image)
normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1
data[0] = normalized_image_array

prediction = model.predict(data)
index = np.argmax(prediction)
class_name = class_names[index]
confidence_score = prediction[0][index]

print("Class:", class_name[2:].strip())
print("Confidence Score:", confidence_score)

